from __future__ import annotations

from .recruitment_runtime import NightshiftRecruitmentService


RETAIL_STARTING_DEPOSIT_CAP = 100_000


def _capped_candidate_summary(summary: str | None, deposit: int) -> str:
    lines = (summary or "").splitlines()
    replacement = f"Готовый депозит: {deposit:,} ₽"
    for index, line in enumerate(lines):
        if line.startswith("Готовый депозит:"):
            lines[index] = replacement
            return "\n".join(lines)
    if lines:
        lines.append(replacement)
        return "\n".join(lines)
    return replacement


class RetailDepositCappedRecruitmentService(NightshiftRecruitmentService):
    """Recruitment with a realistic starting-deposit ceiling for retail couriers.

    The cap applies only to the deposit a courier brings when hired. An employee's
    deposit may later grow above this amount through payroll contributions.
    Wholesale candidates keep their separate, much larger deposit range.
    """

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        with self.db.connect() as conn:
            # Existing drafts and unresolved campaigns should not keep an impossible
            # retail requirement after the balance rule changes.
            conn.execute(
                """UPDATE recruitment_drafts
                   SET min_deposit=?
                   WHERE role='courier' AND min_deposit>?""",
                (RETAIL_STARTING_DEPOSIT_CAP, RETAIL_STARTING_DEPOSIT_CAP),
            )
            conn.execute(
                """UPDATE recruitment_campaigns
                   SET min_deposit=?
                   WHERE role='courier' AND status='active' AND min_deposit>?""",
                (RETAIL_STARTING_DEPOSIT_CAP, RETAIL_STARTING_DEPOSIT_CAP),
            )

            # Open applications generated by an older build are still hireable, so
            # normalize those too. Existing employees are intentionally untouched.
            candidates = conn.execute(
                """SELECT id, deposit, min_deposit, summary
                   FROM candidates
                   WHERE role='courier' AND status='open' AND deposit>?""",
                (RETAIL_STARTING_DEPOSIT_CAP,),
            ).fetchall()
            for candidate in candidates:
                conn.execute(
                    """UPDATE candidates
                       SET deposit=?, min_deposit=?, summary=?
                       WHERE id=?""",
                    (
                        RETAIL_STARTING_DEPOSIT_CAP,
                        min(int(candidate["min_deposit"] or 0), RETAIL_STARTING_DEPOSIT_CAP),
                        _capped_candidate_summary(candidate["summary"], RETAIL_STARTING_DEPOSIT_CAP),
                        candidate["id"],
                    ),
                )

    def ensure_draft(self, player_id: int, channel: str | None = None):
        draft = super().ensure_draft(player_id, channel)
        if draft["role"] == "courier" and int(draft["min_deposit"]) > RETAIL_STARTING_DEPOSIT_CAP:
            with self.db.connect() as conn:
                conn.execute(
                    "UPDATE recruitment_drafts SET min_deposit=? WHERE player_id=?",
                    (RETAIL_STARTING_DEPOSIT_CAP, player_id),
                )
            draft = super().ensure_draft(player_id, channel)
        return draft

    def update_draft(self, player_id: int, field: str, value) -> None:
        if field == "min_deposit":
            draft = self.ensure_draft(player_id)
            if draft["role"] == "courier":
                value = min(RETAIL_STARTING_DEPOSIT_CAP, int(value))
        super().update_draft(player_id, field, value)

    def adjust_draft(self, player_id: int, field: str, delta: int) -> None:
        super().adjust_draft(player_id, field, delta)
        if field != "min_deposit":
            return
        draft = self.ensure_draft(player_id)
        if draft["role"] == "courier" and int(draft["min_deposit"]) > RETAIL_STARTING_DEPOSIT_CAP:
            super().update_draft(player_id, "min_deposit", RETAIL_STARTING_DEPOSIT_CAP)

    def _create_candidate(self, conn, player_id: int, campaign, channel, now) -> None:
        before_id = int(
            conn.execute(
                "SELECT COALESCE(MAX(id),0) FROM candidates WHERE player_id=?",
                (player_id,),
            ).fetchone()[0]
        )
        super()._create_candidate(conn, player_id, campaign, channel, now)

        if campaign["role"] != "courier":
            return
        candidate = conn.execute(
            """SELECT id, deposit, min_deposit, summary
               FROM candidates
               WHERE player_id=? AND id>?
               ORDER BY id DESC LIMIT 1""",
            (player_id, before_id),
        ).fetchone()
        if not candidate:
            return

        deposit = min(int(candidate["deposit"]), RETAIL_STARTING_DEPOSIT_CAP)
        min_deposit = min(int(candidate["min_deposit"] or 0), RETAIL_STARTING_DEPOSIT_CAP)
        if deposit != int(candidate["deposit"]) or min_deposit != int(candidate["min_deposit"] or 0):
            conn.execute(
                """UPDATE candidates
                   SET deposit=?, min_deposit=?, summary=?
                   WHERE id=?""",
                (
                    deposit,
                    min_deposit,
                    _capped_candidate_summary(candidate["summary"], deposit),
                    candidate["id"],
                ),
            )
